name: doc_build_workflow

on:
  push:
    branches:
      - 'main'
    tags:
      - v**

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:  
      - name: Checkout
        uses: actions/checkout@v4    
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip        
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Make docs
        run: |
          pwd
          ls
          cd docs/
          make clean
          make html  
          cd ..
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'  
      - name: Force push to destination branch
        uses: zyrouge/github-push-action@v1
        with:
          directory: ./docs/build/html
          branch: docs
          github-token: ${{ secrets.GITHUB_TOKEN }}

